version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pylon-db:/var/lib/postgresql/pylon
    environment:
      - POSTGRES_NAME=pylon
      - POSTGRES_USER=pylon
      - POSTGRES_PASSWORD=pylon

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://pylon:pylon@db:5432/pylon
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - USE_DOCKER=False
    depends_on:
      - db

volumes:
  pylon-db: