# Generated by Django 3.1.12 on 2021-09-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
