# Generated by Django 3.1.12 on 2021-10-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20210920_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationassemblyitem',
            options={'ordering': ['order']},
        ),
    ]
