# Generated by Django 3.1.12 on 2021-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_auto_20211008_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
