# Generated by Django 3.1.12 on 2021-07-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='vendors.Vendor'),
        ),
    ]
