# Generated by Django 3.1.12 on 2021-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='on_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
