# Generated by Django 3.1.12 on 2021-09-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210901_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='on_order',
            new_name='in_order',
        ),
    ]
