# Generated by Django 3.1.12 on 2021-09-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210903_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinstance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
