# Generated by Django 3.1.12 on 2021-09-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20210901_1808'),
        ('inventory', '0007_auto_20210903_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvendor',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
