# Generated by Django 3.1.12 on 2021-09-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='Stock2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
    ]
