# Generated by Django 3.1.12 on 2021-09-05 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_auto_20210901_1808'),
        ('inventory', '0013_assembly2_stock2'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=32)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryinstance_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryvendor_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='document',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='labor',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='documentvendor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentvendor',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentvendor',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='documentvendor',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='labor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labor',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='laborvendor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='laborvendor',
            name='labor',
        ),
        migrations.RemoveField(
            model_name='laborvendor',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='laborvendor',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='stockinstance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockinstance',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='stockinstance',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stockvendor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockvendor',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='stockvendor',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stockvendor',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Assembly2',
        ),
        migrations.CreateModel(
            name='Labor2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['part_number']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='in_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('e', 'Per Unit'), ('l', 'Per Length')], default='e', max_length=64),
        ),
        migrations.DeleteModel(
            name='Assembly',
        ),
        migrations.DeleteModel(
            name='AssemblyItem',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentVendor',
        ),
        migrations.DeleteModel(
            name='Labor',
        ),
        migrations.DeleteModel(
            name='LaborVendor',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockInstance',
        ),
        migrations.DeleteModel(
            name='StockVendor',
        ),
        migrations.AddField(
            model_name='inventoryvendor',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryvendor',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryvendor_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryvendor',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='inventoryinstance',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryinstance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryinstance_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
