# Generated by Django 3.1.12 on 2021-09-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210905_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labor2',
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
    ]
