# Generated by Django 3.1.12 on 2021-09-05 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0017_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='AssemblyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('s', 'Stock'), ('l', 'Labor'), ('d', 'Document')], default='s', max_length=64)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assembly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblyitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_document', to='inventory.document')),
                ('labor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_labor', to='inventory.labor')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblyitem_modified_by', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_stock', to='inventory.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
