# Generated by Django 3.1.12 on 2021-09-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_assemblyitem_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyItemDocument',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='AssemblyItemLabor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
        migrations.CreateModel(
            name='AssemblyItemStock',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventory',),
        ),
    ]
