# Generated by Django 3.1.12 on 2021-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_inventoryinstance_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
