# Generated by Django 3.1.12 on 2021-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210905_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=32, null=True),
        ),
    ]
