# Generated by Django 3.1.12 on 2021-09-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210905_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyitem',
            name='document',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='labor',
        ),
        migrations.RemoveField(
            model_name='assemblyitem',
            name='stock',
        ),
    ]
