# Generated by Django 3.1.12 on 2021-09-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210909_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_item', to='inventory.inventory'),
            preserve_default=False,
        ),
    ]
