# Generated by Django 3.1.12 on 2021-09-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_assemblyitem_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='assemblyitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True),
        ),
    ]
