# Generated by Django 5.1.4 on 2024-12-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_entity_is_active_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='icon',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='entity',
            name='photo',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
