# Generated by Django 5.1.4 on 2024-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_entity_icon_entity_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entity',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
