# Generated by Django 5.1.4 on 2024-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_entity_created_at_alter_entity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
