# Generated by Django 5.1.4 on 2024-12-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_entity_name_alter_entity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
