# Generated by Django 5.1.4 on 2025-01-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_entity_icon_alter_entity_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='photo',
        ),
    ]
