# Generated by Django 5.1.4 on 2025-01-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_entityicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['-name']},
        ),
    ]
