# Generated by Django 5.1.4 on 2025-01-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_alter_entity_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entity',
            name='idx_created_year',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='idx_created_month',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='idx_created_day',
        ),
    ]
