# Generated by Django 5.1.4 on 2025-01-02 06:45

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_remove_entity_idx_created_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(django.db.models.functions.datetime.ExtractYear('created_at'), name='entity_year_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(django.db.models.functions.datetime.ExtractMonth('created_at'), name='entity_month_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(django.db.models.functions.datetime.ExtractDay('created_at'), name='entity_day_idx'),
        ),
        migrations.AddIndex(
            model_name='entityicon',
            index=models.Index(django.db.models.functions.datetime.ExtractYear('created_at'), name='entity_icon_year_idx'),
        ),
        migrations.AddIndex(
            model_name='entityicon',
            index=models.Index(django.db.models.functions.datetime.ExtractMonth('created_at'), name='entity_icon_month_idx'),
        ),
        migrations.AddIndex(
            model_name='entityicon',
            index=models.Index(django.db.models.functions.datetime.ExtractDay('created_at'), name='entity_icon_day_idx'),
        ),
    ]
