# Generated by Django 5.1.4 on 2025-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_entity_entity_year_idx_entity_entity_month_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
