# Generated by Django 5.1.4 on 2025-01-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_alter_member_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
