name: Pylon Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: SSH connect
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PYLON_HOST }}
        username: ${{ secrets.PYLON_USERNAME }}
        key: ${{ secrets.PYLON_KEY }}
        port: ${{ secrets.PYLON_PORT }}
        script: |
          cd pylon
          git pull
          workon pylon
          pip install -r requirements/local.txt